import localFont from "next/font/local";
import "./globals.css";
import Card from "./main";
import Navbar from "./navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
    <head>
      <title>Quiz</title>
    </head>
    <body className="font-poppins min-h-screen overflow-auto">
      <header className="h-auto">
        <Navbar />
      </header>
      <main className="h-full">
        <Card /> {/* Your landing page will be displayed here without scrolling */}
        {children}
      </main>
    </body>
  </html>
  );
}
